config/routes.rb
TestApp::Application.routes.draw do
  resources :users

  resources :tests

  resources :notes

  resources :user_sessions

  match '/signin' => 'user_sessions#new'

  match '/signout' => 'user_sessions#destroy'

  root :to => "notes#index"

end

app/models/note.rb
class Note < ActiveRecord::Base
	validates_presence_of :title
end

app/models/test.rb
class Test

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base



end

app/controllers/application_controller.rb
class ApplicationController <ActionController::Base

  filter_parameter_logging :password

  helper_method :current_user

  private

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.record
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @search = Note.search(params[:search])
    binding.pry
    @notes = @search.all
    @title = view_context.title_helper("dogs are awesome")
  end

  def new
    @note = Note.new

    
  end

  def create
    @note = Note.new(params[:note])
    if @note.save
      redirect_to(@note, notice: 'Note was saved successfully')
    else
      render 'new'
    end
  end

  def show
    @note = Note.find(params[:id])
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to(notes_path) }
      format.xml  { head :ok }
    end
  end


end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  # GET /tests
  # GET /tests.xml
  def index
    @tests = Test.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tests }
    end
  end

  # GET /tests/1
  # GET /tests/1.xml
  def show
    @test = Test.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @test }
    end
  end

  # GET /tests/new
  # GET /tests/new.xml
  def new
    @test = Test.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @test }
    end
  end

  # GET /tests/1/edit
  def edit
    @test = Test.find(params[:id])
  end

  # POST /tests
  # POST /tests.xml
  def create
    @test = Test.new(params[:test])

    respond_to do |format|
      if @test.save
        format.html { redirect_to(@test, :notice => 'Test was successfully created.') }
        format.xml  { render :xml => @test, :status => :created, :location => @test }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @test.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tests/1
  # PUT /tests/1.xml
  def update
    @test = Test.find(params[:id])

    respond_to do |format|
      if @test.update_attributes(params[:test])
        format.html { redirect_to(@test, :notice => 'Test was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @test.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.xml
  def destroy
    @test = Test.find(params[:id])
    @test.destroy

    respond_to do |format|
      format.html { redirect_to(tests_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Successfully logged in."
      redirect_to root_url
    else
      render :action => 'new'
    end
  end

  def destroy
    @user_session = UserSession.find
    @user_session.destroy
    flash[:notice] = "Successfully logged out."
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = current_user
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'Registration Successful') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'Successful Update') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title_helper(str)
    str.titleize
  end
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title TestApp
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag

  %body
    #user_nav
      - if current_user
        = link_to "Edit Profile", edit_user_path(:current)
        = link_to "Logout", signout_path
      - else
        =link_to "Register", new_user_path |
        =link_to "Login", signin_path

    - flash.each do |name, msg|
      =content_tag :div, msg, :id => "flash_#{name}"

    .main-wrapper
      = yield

app/views/notes/_form.html.haml
- semantic_form_for @note do |f|
  - f.inputs do
    =f.input :title
    =f.input :body
  = f.buttons

app/views/notes/index.html.haml
%h2 Formtastic Form
=semantic_form_for @search do |f|
  -f.inputs do
    =f.input :title_contains
    =f.input :created_at_less_than
  -f.buttons do
    =f.submit "Search"

%h2 rails form helper
= form_for @search do |f|
  =f.label :title_contains
  =f.text_field :title_contains
  .button= f.submit "Search"

%h2== Results - #{@title}
%ul
  - @notes.each do |note|
    %li
      =link_to note.title, note_path(note)
      =link_to 'destroy note', note, confirm: 'Are you sure?', :method => :delete

=link_to 'New Note', new_note_path

app/views/notes/new.html.haml
New Note

= render 'form'

app/views/notes/show.html.haml
=@note.title

=@note.body


%p== Please navigate to the following web address #{link_to "http://jobs.3playmedia.com", "http://jobs.3playmedia.com"} and login to your account using the below information. Again, be sure you are using Google Chrome or Safari. If you simply click on the above link your computer may open your default web browser, such as Internet Explorer or Mozilla Firefox.
%p== Login: <b>#{@note.title}</b><br>Password: <b>password</b>

%p== Please navigate to the following web address to create a password and access your account!
%p== Login: <b>#{@note.title}</b>
  
%p== #{link_to notes_url, notes_url}


=link_to "Back", notes_path

app/views/user_sessions/new.html.haml
%title Login
%h2 Login

=form_for @user_session do |f|
  %p
    =f.label :username
    =f.text_field :username
  %p
    =f.label :password
    =f.password_field :password
  %p
    =f.submit "Submit"

app/views/users/_form.html.haml
=form_for @user do |f|
  %p
    =f.label :username
    =f.text_field :username
  %p
    =f.label :email
    =f.text_field :email
  %p
    =f.label :password
    =f.password_field :password
  %p
    =f.label :password_confirmation
    =f.password_field :password_confirmation
  %p
    =f.submit "Submit"

app/views/users/edit.html.haml
%h1 Editing User

= render 'form'

= link_to 'Show', @user |
= link_to 'Back', users_path

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.haml
%h1 New User

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>